*** empty log message ***

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1039,6 +1039,7 @@ Optional Features:
   --enable-xpm-background enable XPM background pixmaps
   --enable-transparency   enable transparent backgrounds
   --enable-tinting        enable tinting of transparent bg
+  --enable-fading         enable colors fading when off focus
   --enable-menubar        enable menubar
   --enable-rxvt-scroll    enable rxvt style scrollbar
   --enable-next-scroll    enable NeXT style scrollbar
@@ -5237,7 +5238,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case "$host" in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5240 "configure"' > conftest.$ac_ext
+  echo '#line 5241 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5788,7 +5789,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:5791: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:5792: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -7404,7 +7405,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 7407 "configure"
+#line 7408 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -7502,7 +7503,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 7505 "configure"
+#line 7506 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8236,6 +8237,7 @@ support_frills=no
 support_linespace=no
 support_inheritpixmap=no
 support_tinting=no
+support_fading=no
 support_keepscrolling=no
 support_selectionscrolling=no
 support_menubar=no
@@ -8279,6 +8281,7 @@ if test "${enable_everything+set}" = set; then
     support_linespace=yes
     support_inheritpixmap=yes
     support_tinting=yes
+    support_fading=yes
     support_keepscrolling=yes
     support_selectionscrolling=yes
     support_lastlog=yes
@@ -8373,6 +8376,14 @@ if test "${enable_tinting+set}" = set; then
   enableval="$enable_tinting"
   if test x$enableval = xyes -o x$enableval = xno; then
     support_tinting=$enableval
+  fi
+fi;
+
+# Check whether --enable-fading or --disable-fading was given.
+if test "${enable_fading+set}" = set; then
+  enableval="$enable_fading"
+  if test x$enableval = xyes -o x$enableval = xno; then
+    support_fading=$enableval
   fi
 fi;
 
@@ -16189,6 +16200,64 @@ _ACEOF
 
 fi
 
+echo "$as_me:$LINENO: checking for broken XIM callback" >&5
+echo $ECHO_N "checking for broken XIM callback... $ECHO_C" >&6
+if test "${rxvt_broken_ximcb+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+
+#include <X11/Xlib.h>
+
+void im_destroy_cb (XIC unused1, XPointer client_data, XPointer unused3);
+
+void f() {
+  XIMCallback cb;
+  cb.callback = im_destroy_cb;
+}
+
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  rxvt_broken_ximcb=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+rxvt_broken_ximcb=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $rxvt_broken_ximcb" >&5
+echo "${ECHO_T}$rxvt_broken_ximcb" >&6
+
+if test x$rxvt_broken_ximcb = xyes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define XIMCB_PROTO_BROKEN 1
+_ACEOF
+
+fi
+
 echo "$as_me:$LINENO: checking for getpt" >&5
 echo $ECHO_N "checking for getpt... $ECHO_C" >&6
 if test "${rxvt_cv_func_getpt+set}" = set; then
@@ -16381,6 +16450,13 @@ if test x$support_8bitctrls = xyes; then
 
 cat >>confdefs.h <<\_ACEOF
 #define EIGHT_BIT_CONTROLS 1
+_ACEOF
+
+fi
+if test x$support_fading = xyes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define OFF_FOCUS_FADING 1
 _ACEOF
 
 fi
