*** empty log message ***

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -309,7 +309,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os VERSION DATE LSMDATE LIBVERSION CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX CPP INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA AWK LINKER CXXCPP EGREP INSTALL_LIBRXVT RXVTNAME MV RM CP LN SED ECHO CMP TBL TIC X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS XPM_CPPFLAGS XPM_CFLAGS XPM_LIBS rxvt_int16_typedef rxvt_uint16_typedef rxvt_int32_typedef rxvt_uint32_typedef rxvt_intp_define rxvt_u_intp_define DEBUG DINCLUDE DLIB include_stdint_h include_stdarg_h include_stdlib_h include_unistd_h include_string_h include_fcntl_h include_util_h include_assert_h include_sys_ioctl_h include_sys_select_h include_sys_strredir_h include_sys_time_h include_time_h LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os VERSION DATE LSMDATE LIBVERSION CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX CPP INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA AWK LINKER CXXCPP EGREP INSTALL_LIBRXVT RXVTNAME MV RM CP LN SED ECHO CMP TBL TIC X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS XPM_CPPFLAGS XPM_CFLAGS XPM_LIBS rxvt_int16_typedef rxvt_uint16_typedef rxvt_int32_typedef rxvt_uint32_typedef rxvt_intp_define rxvt_u_intp_define PERL PERLLIB PERLFLAGS PERLARCHLIB IF_PERL PERL_O DEBUG DINCLUDE DLIB include_stdint_h include_stdarg_h include_stdlib_h include_unistd_h include_string_h include_fcntl_h include_util_h include_assert_h include_sys_ioctl_h include_sys_select_h include_sys_strredir_h include_sys_time_h include_time_h LIBOBJS LTLIBOBJS'
 ac_subst_files='MCOMMON'
 
 # Initialize some variables set by options.
@@ -883,6 +883,7 @@ Optional Features:
   --enable-rxvt-scroll    enable rxvt style scrollbar
   --enable-next-scroll    enable NeXT style scrollbar
   --enable-xterm-scroll   enable Xterm style scrollbar
+  --enable-perl           enable embedded perl interpreter
   --enable-plain-scroll   enable plain style scrollbar
   --enable-half-shadow    use half width/height shadow on rxvt scrollbar
   --enable-xim            XIM (X Input Method) protocol support
@@ -4346,6 +4347,7 @@ support_combining=yes
 support_8bitctrls=no
 support_iso14755=yes
 support_styles=yes
+support_perl=no
 codesets=all
 
 
@@ -4391,6 +4393,7 @@ if test "${enable_everything+set}" = set; then
        support_8bitctrls=no
        support_iso14755=no
        support_styles=no
+       support_perl=no
        codesets=
     fi
     if test x$enableval = xyes; then
@@ -4421,6 +4424,7 @@ if test "${enable_everything+set}" = set; then
        #support_8bitctrls=yes
        support_iso14755=yes
        support_styles=yes
+       support_perl=yes
        codesets=all
     fi
 
@@ -4543,6 +4547,14 @@ if test "${enable_xterm_scroll+set}" = set; then
   enableval="$enable_xterm_scroll"
   if test x$enableval = xyes -o x$enableval = xno; then
     support_scroll_xterm=$enableval
+  fi
+fi;
+
+# Check whether --enable-perl or --disable-perl was given.
+if test "${enable_perl+set}" = set; then
+  enableval="$enable_perl"
+  if test x$enableval = xyes -o x$enableval = xno; then
+    support_perl=$enableval
   fi
 fi;
 
@@ -12644,6 +12656,115 @@ _ACEOF
   esac
 done
 
+IF_PERL=\#
+if test x$support_perl = xyes; then
+  # Extract the first word of "perl5", so it can be a program name with args.
+set dummy perl5; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_PERL+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $PERL in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PERL="$PERL" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_PERL="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+PERL=$ac_cv_path_PERL
+
+if test -n "$PERL"; then
+  echo "$as_me:$LINENO: result: $PERL" >&5
+echo "${ECHO_T}$PERL" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  # Extract the first word of "perl", so it can be a program name with args.
+set dummy perl; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_PERL+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $PERL in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PERL="$PERL" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_PERL="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+PERL=$ac_cv_path_PERL
+
+if test -n "$PERL"; then
+  echo "$as_me:$LINENO: result: $PERL" >&5
+echo "${ECHO_T}$PERL" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+  echo "$as_me:$LINENO: checking for $PERL suitability" >&5
+echo $ECHO_N "checking for $PERL suitability... $ECHO_C" >&6
+  if $PERL -MExtUtils::Embed -e "use v5.8" >/dev/null 2>/dev/null; then
+
+cat >>confdefs.h <<\_ACEOF
+#define ENABLE_PERL 1
+_ACEOF
+
+     IF_PERL=
+     PERL_O=rxvtperl.o
+     PERLFLAGS="`$PERL -MExtUtils::Embed -e ccopts`"
+     PERLLIB="`$PERL -MExtUtils::Embed -e ldopts`"
+     PERLARCHLIB="`$PERL -MConfig -e 'print $Config{archlib}'`"
+     echo "$as_me:$LINENO: result: ok" >&5
+echo "${ECHO_T}ok" >&6
+  else
+     { { echo "$as_me:$LINENO: error: no working perl found" >&5
+echo "$as_me: error: no working perl found" >&2;}
+   { (exit or perl not version >= 5.8); exit or perl not version >= 5.8; }; }
+  fi
+fi
+
+
+
+
+
+
+
 
 CFLAGS=${CFLAGS--O}
 LDFLAGS=${LDFLAGS--O}
@@ -13433,6 +13554,12 @@ s,@rxvt_int32_typedef@,$rxvt_int32_typedef,;t t
 s,@rxvt_uint32_typedef@,$rxvt_uint32_typedef,;t t
 s,@rxvt_intp_define@,$rxvt_intp_define,;t t
 s,@rxvt_u_intp_define@,$rxvt_u_intp_define,;t t
+s,@PERL@,$PERL,;t t
+s,@PERLLIB@,$PERLLIB,;t t
+s,@PERLFLAGS@,$PERLFLAGS,;t t
+s,@PERLARCHLIB@,$PERLARCHLIB,;t t
+s,@IF_PERL@,$IF_PERL,;t t
+s,@PERL_O@,$PERL_O,;t t
 s,@DEBUG@,$DEBUG,;t t
 s,@DINCLUDE@,$DINCLUDE,;t t
 s,@DLIB@,$DLIB,;t t
@@ -13983,7 +14110,8 @@ else
   wtmp file:                  $rxvt_cv_path_wtmp
   wtmpx file:                 $rxvt_cv_path_wtmpx
   lastlog file:               $rxvt_cv_path_lastlog
-  ttys/ttytab file:           $rxvt_cv_path_ttytab"
+  ttys/ttytab file:           $rxvt_cv_path_ttytab
+  embedded perl:              $support_perl"
   echo
 fi
 if test x$term != x; then
